### ISSUE TITLE
CKAN Docker build from scratch fails

### ISSUE THREAD

**Issue by akariv** [hasadna/ckan-cloud-docker#1]
This is the error message
```
Step 18/50 : RUN touch $CKAN_VENV/src/ckan/requirement-setuptools.txt && ckan-pip install --index-url ${PIP_INDEX_URL:-https://pypi.org/simple/} --upgrade --no-cache-dir -r $CKAN_VENV/src/ckan/requirement-setuptools.txt
 ---> Running in 25a065793f59
Traceback (most recent call last):
  File "/usr/local/bin/ckan-pip", line 9, in <module>
    load_entry_point('pip==21.0.1', 'console_scripts', 'pip')()
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

**Comment by OriHoch** [comment]
please write the docker build command you used

**Comment by akariv** [comment]
I followed the instructions in the README

**Comment by akariv** [comment]
Perhaps this message is also related:

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020.
Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0
will drop support for Python 2.7 in January 2021. More details about Python
2 support in pip, can be found at
https://pip.pypa.io/en/latest/development/release-process/#python-2-support

**Comment by OriHoch** [comment]
thanks, fixed
